server:
  ## Prometheus server container name
  ##
  name: server

  env: []

  # configPath: /etc/config/prometheus.yml

  persistentVolume:
    enabled: true

    mountPath: /data
    size: 10Gi

  replicaCount: 1

  service:
    ## If false, no Service will be created for the Prometheus server
    ##
    enabled: true

    type: LoadBalancer

## Prometheus server ConfigMap entries
##
serverFiles:
  prometheus.yml:
    rule_files:
      - /data/django.rules

    scrape_configs:
      - job_name: django
        static_configs:
          - targets:
              - lion-app
