apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lion.db.fullname" . }}
type: Opaque
data:
  POSTGRES_DB: bGlvbmZvcnVt
  POSTGRES_USER: bGlvbg==
  POSTGRES_PASSWORD: dGlnZXI=
  POSTGRES_PORT: NTQzMg==
