apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "simple-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "simple-web.selectorLabels" . | nindent 4}}
  ports:
    - port: 80
      targetPort: 8000
