apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-configmap
    labels:
{{ include "mychart.app" . | indent 8 }}
data:
    myvalue: "Hello World"
    {{- range $key, $val := .Values.favorites }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    toppings: |-
        {{- range $index, $topping := .Values.pizzaToppings }}
        {{ $index }}: {{ $topping | title | quote }}
        {{- end }}
    sizes: |-
        {{- range tuple "small" "medium" "large" }}
        - {{ . }}
        {{- end }}
{{ include "mychart.app" . | indent 4 }}
